### PR TITLE
Allow to run single fixtures with all their dependencies (recursively)

### PR DESCRIPTION
**Pull request by jkniest**

### CODE REVIEW

**Comment by jkniest** [comment]
On merge, I will squash all commits down into one commit

**Comment by boxblinkracer** [comment]
nice one, makes sense :)

**Comment by boxblinkracer** [comment]
do you want to update the README too on that?
i'm approving, but maybe you want to add some instructions in the readme too

**Review by boxblinkracer — APPROVED** [review]

**Review by jdambacher — APPROVED** [review]

**Comment by jkniest** [comment]
Hey, we require this version right know. I will merge and tag this and make another merge request for the readme tomorrow

**Pull request merged**
