### PR TITLE
NTR: add helpers with fluent approach

### PR DESCRIPTION
**Pull request by boxblinkracer**
WORK IN PROGRESS!!!!

fluent approach with backward compatibility?
would prepare the helpers in case more features come

what do you think?

### CODE REVIEW

**Comment by jdambacher** [comment]
LGTM, but please don't use PHPDoc comments when using type hints.

**Comment by boxblinkracer** [comment]
done

**Review by jkniest — APPROVED** [review]
lgtm

**Comment by boxblinkracer** [comment]
just renamed the names of the util functions to be more accurate and shorter
and removed the deprecated functions as discussed in slack

**Review by jdambacher — APPROVED** [review]

**Pull request merged**
